apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Capstone-Cluster
  region: us-east-1

vpc:
  id: vpc-0c89bcc4455175379
  cidr: "192.168.0.0/16"
  subnets:
    public:
      my-new-stack-PublicSubnet01:
        id: subnet-0d5e560ac334fbf1b
      my-new-stack-PublicSubnet02:
        id: subnet-03696f16047b59a91
    private:
      my-new-stack-PrivateSubnet01:
        id: subnet-098fae3ef2dd41a08
      my-new-stack-PrivateSubnet02:
        id: subnet-088be02cabc02ff54

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true
