apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Capstone-Cluster
  region: us-east-1

vpc:
  id: vpc-06f6ab68ec29856bb
  cidr: "192.168.0.0/16"
  subnets:
    public:
      my-new-stack-PublicSubnet01:
        id: subnet-0b6244f063321faed
      my-new-stack-PublicSubnet02:
        id: subnet-0458cdc767b4760db
    private:
      my-new-stack-PrivateSubnet01:
        id: subnet-009c737ca58f33842
      my-new-stack-PrivateSubnet02:
        id: subnet-089662ba7f1c808af

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true
