apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-server
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: capstone-project-container
          image: ${AWS_ECR_URL}:${VERSION}
          ports:
            # - containerPort: 80
            - containerPort: 5000
