apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-server
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: capstone-project-container
          image: 343591568300.dkr.ecr.us-east-1.amazonaws.com/capstone-project:latest
          ports:
            - containerPort: 5000
