apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-server
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: capstone-project-container
          image: 343591568300.dkr.ecr.us-east-1.amazonaws.com/capstone-project:latest
          ports:
            # - containerPort: 80
            - containerPort: 5000
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: flaskapi
#   namespace: default
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: flaskapi
#   template:
#     metadata:
#       labels:
#         app: flaskapi
#     spec:
#       containers:
#         - name: flaskapi
#           image: ${AWS_ECR_URL}:latest
#           ports:
#             - containerPort: 80
