apiVersion: v1
kind: Service
metadata:
  name: capstone-project-service
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - nodePort: 31479
      port: 5000
      targetPort: 80
      # port: 80
      # targetPort: 5000
