apiVersion: v1
kind: Service
metadata:
  name: capstone-project-service
spec:
  type: LoadBalancer
  ports:
    - nodePort: 31479
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: web
