# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

jobs:
  lint-docker:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Create virtual env
          command: |
            python3 -m venv venv
            . venv/bin/activate
      - run:
          name: Install dependencies
          command: |
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Run linters
          command: |
            . venv/bin/activate
              make lint

  build-and-push-docker-image:
    docker:
      - image: guitarrapc/docker-awscli-kubectl
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Ensure ECR exists
          command: |
            aws ecr describe-repositories --repository-names ${REPO_NAME} || aws ecr create-repository --repository-name ${REPO_NAME}

      - run:
          name: Push application Docker image
          command: |
            export ECR_AWS_URI=$(aws ecr describe-repositories \
              --repository-names ${REPO_NAME} \
              --query 'repositories[*].repositoryUri' \
              --output text)
            echo ECR_AWS_URI: ${ECR_AWS_URI}
            echo CIRCLE_BRANCH: ${CIRCLE_BRANCH}
            echo REPO_NAME: ${REPO_NAME}
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              aws ecr get-login-password --region us-east-1 | docker login\
              --username AWS --password-stdin\
              ${ECR_AWS_URI}
              docker build -t capstone-project .
              docker tag ${REPO_NAME}:latest ${ECR_AWS_URI}:latest
              docker push ${ECR_AWS_URI}:latest
            fi

  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure aws infrastructure exists
          command: |
            aws cloudformation deploy \
              --template-file aws-infra.yml \
              --tags project=capstone \
              --stack-name "capstone-project" \
              --parameter-overrides ID="capstone-project"

      - run:
          name: Spin up ECS cluster
          command: |
            eksctl create cluster -f cluster.yml

workflows:
  deployment:
    jobs:
      - lint-docker
      - build-and-push-docker-image
      - deploy-infrastructure:
          requires: [build-and-push-docker-image]
# Build environment to lint project files - DONE
# Lint docker image and python files - DONE
# Create ECR repo (or check it exists) - DONE
# Build docker image/push docker image - DONE
# Create rest of AWS infra
# Create clusters - eksctl create cluster
# Apply deployment to clusters
