# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

jobs:
  build-env:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Create virtual env
          command: |
            python3 -m venv venv
            . venv/bin/activate
      - run:
          name: Install dependencies
          command: |
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Run linters
          command: |
            . venv/bin/activate
              make lint

  build-docker-image:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-${CIRCLE_WORKFLOW_ID:0:7}
          paths:
            - /caches/app.tar

  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: yum -y install tar gzip
      - restore_cache:
          keys:
            - v1-{{ .Branch }}-${CIRCLE_WORKFLOW_ID:0:7}
      - run:
          name: Ensure ECR exists
          command: |
            aws ecr describe-repositories --repository-names ${REPO_NAME} || aws ecr create-repository --repository-name ${REPO_NAME}
      - run:
          name: Add ECR URI to inventory
          command: |
            export ECR_AWS_URI=$(aws ecr describe-repositories \
              --repository-names ${REPO_NAME} \
              --query 'repositories[*].repositoryUri' \
              --output text)
            echo "$ECR_AWS_URI" >> inventory.txt              
            pwd
            cat inventory.txt
            echo ${ECR_AWS_URI} = "${ECR_AWS_URI}"
      - persist_to_workspace:
          root: ~/
          paths:
            - project/inventory.txt
      - run:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${ECR_ENDPOINT}
              docker tag ${REPO_NAME}:latest ${ECR_ENDPOINT}:latest
              docker push ${ECR_ENDPOINT}:latest
            fi
      # - run:
      #     name: Ensure aws infrastructure exists
      #     command: |
      #       aws cloudformation deploy \
      #         --template-file aws-infra.yml \
      #         --tags project=captstone \
      #         --stack-name "capstone-${CIRCLE_WORKFLOW_ID:0:7}" \
      #         --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"

workflows:
  deployment:
    jobs:
      - build-env
      - build-docker-image
      - deploy-infrastructure:
          requires: [build-docker-image]
# Build environment
# Lint docker image
# Build docker image
# Create ECR repo (or check it exists)
# Need to save ECR endpoint so that it's accessible
# Create rest of AWS infra
